import { pool } from "../config/pool.js";

const columnExists = async (tableName, columnName) => {
  const { rows } = await pool.query(
    `SELECT EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2
    ) AS exists`,
    [tableName, columnName],
  );
  return rows[0].exists;
};

const indexExists = async (indexName) => {
  const { rows } = await pool.query(
    `SELECT EXISTS (
      SELECT 1
      FROM pg_indexes
      WHERE schemaname = 'public' AND indexname = $1
    ) AS exists`,
    [indexName],
  );
  return rows[0].exists;
};

const constraintExists = async (constraintName) => {
  const { rows } = await pool.query(
    `SELECT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = $1
    ) AS exists`,
    [constraintName],
  );
  return rows[0].exists;
};

const ensureBaseTables = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS departments (
      department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      code VARCHAR(20) NOT NULL UNIQUE,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS terms (
      term_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      academic_year VARCHAR(10) NOT NULL,
      semester VARCHAR(2) NOT NULL CHECK (semester IN ('I', 'II')),
      UNIQUE (academic_year, semester)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS teachers (
      teacher_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(100) NOT NULL UNIQUE,
      department_id INTEGER NOT NULL REFERENCES departments(department_id) ON DELETE RESTRICT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS subjects (
      subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      code VARCHAR(20) NOT NULL UNIQUE,
      department_id INTEGER NOT NULL REFERENCES departments(department_id) ON DELETE RESTRICT,
      total_mark INTEGER NOT NULL DEFAULT 100,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS classes (
      class_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      class_name VARCHAR(20) NOT NULL,
      grade VARCHAR(2) NOT NULL CHECK (grade IN ('9', '10', '11', '12')),
      homeroom_teacher_id INTEGER NOT NULL REFERENCES teachers(teacher_id) ON DELETE RESTRICT,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS students (
      student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      student_school_id VARCHAR(20),
      name VARCHAR(100) NOT NULL,
      gender VARCHAR(1),
      class_id INTEGER,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS marks (
      mark_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      student_id INTEGER NOT NULL REFERENCES students(student_id) ON DELETE RESTRICT,
      subject_id INTEGER NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
      mark_obtained INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);
};

const ensureReferenceData = async () => {
  const dept = await pool.query(
    `INSERT INTO departments (name, code)
     VALUES ($1, $2)
     ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name
     RETURNING department_id`,
    ["General", "GEN"],
  );

  const teacher = await pool.query(
    `INSERT INTO teachers (name, email, department_id)
     VALUES ($1, $2, $3)
     ON CONFLICT (email) DO UPDATE SET
       name = EXCLUDED.name,
       department_id = EXCLUDED.department_id
     RETURNING teacher_id`,
    [
      "Unassigned Homeroom",
      "homeroom.unassigned@school.local",
      dept.rows[0].department_id,
    ],
  );

  const term = await pool.query(
    `INSERT INTO terms (academic_year, semester)
     VALUES ($1, $2)
     ON CONFLICT (academic_year, semester)
     DO UPDATE SET academic_year = EXCLUDED.academic_year
     RETURNING term_id`,
    ["2024-2025", "I"],
  );

  return {
    teacherId: teacher.rows[0].teacher_id,
    defaultTermId: term.rows[0].term_id,
  };
};

const seedTermsFromLegacyColumns = async () => {
  const classHasAcademicYear = await columnExists("classes", "academic_year");
  const classHasSemester = await columnExists("classes", "semester");
  const markHasAcademicYear = await columnExists("marks", "academic_year");
  const markHasSemester = await columnExists("marks", "semester");
  const studentHasAcademicYear = await columnExists(
    "students",
    "academic_year",
  );
  const studentHasSemester = await columnExists("students", "semester");

  if (classHasAcademicYear && classHasSemester) {
    await pool.query(`
      INSERT INTO terms (academic_year, semester)
      SELECT DISTINCT academic_year, semester
      FROM classes
      WHERE academic_year IS NOT NULL AND semester IS NOT NULL
      ON CONFLICT (academic_year, semester) DO NOTHING
    `);
  }

  if (markHasAcademicYear && markHasSemester) {
    await pool.query(`
      INSERT INTO terms (academic_year, semester)
      SELECT DISTINCT academic_year, semester
      FROM marks
      WHERE academic_year IS NOT NULL AND semester IS NOT NULL
      ON CONFLICT (academic_year, semester) DO NOTHING
    `);
  }

  if (studentHasAcademicYear && studentHasSemester) {
    await pool.query(`
      INSERT INTO terms (academic_year, semester)
      SELECT DISTINCT academic_year, semester
      FROM students
      WHERE academic_year IS NOT NULL AND semester IS NOT NULL
      ON CONFLICT (academic_year, semester) DO NOTHING
    `);
  }
};

const recreateReportView = async () => {
  await pool.query("DROP VIEW IF EXISTS student_academic_report_v2");
  await pool.query("DROP VIEW IF EXISTS student_academic_report");
  await pool.query(`
    CREATE VIEW student_academic_report AS
    SELECT
      ranked.*,
      CASE
        WHEN ranked.average_score >= 50 THEN 'PASS'
        ELSE 'FAIL'
      END AS status
    FROM (
      SELECT
        s.student_id,
        s.student_school_id,
        s.name AS student_name,
        s.gender,
        c.class_name,
        c.grade,
        tm.academic_year,
        tm.semester,
        tm.maths_mark,
        tm.english_mark,
        tm.biology_mark,
        tm.chemistry_mark,
        tm.physics_mark,
        (
          COALESCE(tm.maths_mark, 0)
          + COALESCE(tm.english_mark, 0)
          + COALESCE(tm.biology_mark, 0)
          + COALESCE(tm.chemistry_mark, 0)
          + COALESCE(tm.physics_mark, 0)
        ) AS total_marks,
        ROUND((
          COALESCE(tm.maths_mark, 0)
          + COALESCE(tm.english_mark, 0)
          + COALESCE(tm.biology_mark, 0)
          + COALESCE(tm.chemistry_mark, 0)
          + COALESCE(tm.physics_mark, 0)
        )::numeric / 5, 2) AS average_score,
        RANK() OVER (
          PARTITION BY c.grade, tm.academic_year, tm.semester
          ORDER BY (
            COALESCE(tm.maths_mark, 0)
            + COALESCE(tm.english_mark, 0)
            + COALESCE(tm.biology_mark, 0)
            + COALESCE(tm.chemistry_mark, 0)
            + COALESCE(tm.physics_mark, 0)
          ) DESC
        ) AS rank
      FROM students s
      LEFT JOIN classes c ON c.class_id = s.class_id
      INNER JOIN (
        SELECT
          m.student_id,
          t.academic_year,
          t.semester,
          MAX(CASE WHEN LOWER(sub.name) = 'maths' THEN m.mark_obtained END) AS maths_mark,
          MAX(CASE WHEN LOWER(sub.name) = 'english' THEN m.mark_obtained END) AS english_mark,
          MAX(CASE WHEN LOWER(sub.name) = 'biology' THEN m.mark_obtained END) AS biology_mark,
          MAX(CASE WHEN LOWER(sub.name) = 'chemistry' THEN m.mark_obtained END) AS chemistry_mark,
          MAX(CASE WHEN LOWER(sub.name) = 'physics' THEN m.mark_obtained END) AS physics_mark
        FROM marks m
        INNER JOIN subjects sub ON sub.subject_id = m.subject_id
        INNER JOIN terms t ON t.term_id = m.term_id
        GROUP BY m.student_id, t.academic_year, t.semester
      ) tm ON tm.student_id = s.student_id
    ) ranked
  `);
};

const runMigration = async () => {
  try {
    console.log("Starting migration...");
    await pool.query("BEGIN");

    await ensureBaseTables();
    await seedTermsFromLegacyColumns();

    const { teacherId, defaultTermId } = await ensureReferenceData();

    if (!(await columnExists("classes", "term_id"))) {
      await pool.query("ALTER TABLE classes ADD COLUMN term_id INTEGER");
    }

    if (
      (await columnExists("classes", "academic_year")) &&
      (await columnExists("classes", "semester"))
    ) {
      await pool.query(`
        UPDATE classes c
        SET term_id = t.term_id
        FROM terms t
        WHERE c.term_id IS NULL
          AND c.academic_year = t.academic_year
          AND c.semester = t.semester
      `);
    }

    await pool.query("UPDATE classes SET term_id = $1 WHERE term_id IS NULL", [
      defaultTermId,
    ]);
    await pool.query(
      "UPDATE classes SET homeroom_teacher_id = $1 WHERE homeroom_teacher_id IS NULL",
      [teacherId],
    );

    if (!(await constraintExists("fk_classes_term"))) {
      await pool.query(`
        ALTER TABLE classes
        ADD CONSTRAINT fk_classes_term
        FOREIGN KEY (term_id) REFERENCES terms(term_id) ON DELETE RESTRICT
      `);
    }

    if (!(await indexExists("unique_class_term_id"))) {
      await pool.query(
        "CREATE UNIQUE INDEX unique_class_term_id ON classes(class_name, term_id)",
      );
    }

    if (await constraintExists("unique_class_term")) {
      await pool.query("ALTER TABLE classes DROP CONSTRAINT unique_class_term");
    }

    await pool.query("ALTER TABLE classes ALTER COLUMN term_id SET NOT NULL");

    if (
      (await columnExists("classes", "academic_year")) &&
      (await columnExists("classes", "semester"))
    ) {
      await pool.query("ALTER TABLE classes DROP COLUMN academic_year CASCADE");
      await pool.query("ALTER TABLE classes DROP COLUMN semester CASCADE");
    }

    if (!(await columnExists("students", "student_school_id"))) {
      await pool.query(
        "ALTER TABLE students ADD COLUMN student_school_id VARCHAR(20)",
      );
    }

    if (!(await columnExists("students", "gender"))) {
      await pool.query("ALTER TABLE students ADD COLUMN gender VARCHAR(1)");
    }

    if (!(await columnExists("students", "class_id"))) {
      await pool.query("ALTER TABLE students ADD COLUMN class_id INTEGER");
    }

    if (
      (await columnExists("students", "grade")) &&
      (await columnExists("students", "academic_year")) &&
      (await columnExists("students", "semester"))
    ) {
      await pool.query(
        `INSERT INTO classes (class_name, grade, term_id, homeroom_teacher_id)
         SELECT
           s.grade || 'A',
           s.grade,
           t.term_id,
           $1
         FROM students s
         JOIN terms t
           ON t.academic_year = s.academic_year
          AND t.semester = s.semester
         LEFT JOIN classes c
           ON c.grade = s.grade
          AND c.term_id = t.term_id
         WHERE s.class_id IS NULL
           AND c.class_id IS NULL
         GROUP BY s.grade, t.term_id`,
        [teacherId],
      );

      await pool.query(`
        UPDATE students s
        SET class_id = c.class_id
        FROM classes c
        JOIN terms t ON t.term_id = c.term_id
        WHERE s.class_id IS NULL
          AND c.grade = s.grade
          AND s.academic_year = t.academic_year
          AND s.semester = t.semester
      `);
    }

    const fallbackClass = await pool.query(
      `INSERT INTO classes (class_name, grade, term_id, homeroom_teacher_id)
       VALUES ('UNASSIGNED', '9', $1, $2)
       ON CONFLICT (class_name, term_id)
       DO UPDATE SET homeroom_teacher_id = EXCLUDED.homeroom_teacher_id
       RETURNING class_id`,
      [defaultTermId, teacherId],
    );

    await pool.query(
      "UPDATE students SET class_id = $1 WHERE class_id IS NULL",
      [fallbackClass.rows[0].class_id],
    );

    await pool.query(
      "UPDATE students SET student_school_id = 'STD-' || LPAD(student_id::text, 3, '0') WHERE student_school_id IS NULL OR student_school_id = ''",
    );
    await pool.query(
      "UPDATE students SET gender = 'M' WHERE gender IS NULL OR gender = ''",
    );

    if (!(await constraintExists("fk_students_class"))) {
      await pool.query(`
        ALTER TABLE students
        ADD CONSTRAINT fk_students_class
        FOREIGN KEY (class_id) REFERENCES classes(class_id) ON DELETE RESTRICT
      `);
    }

    if (!(await constraintExists("chk_students_gender"))) {
      await pool.query(
        "ALTER TABLE students ADD CONSTRAINT chk_students_gender CHECK (gender IN ('M', 'F'))",
      );
    }

    if (!(await indexExists("uq_students_school_id"))) {
      await pool.query(
        "CREATE UNIQUE INDEX uq_students_school_id ON students(student_school_id)",
      );
    }

    await pool.query(
      "ALTER TABLE students ALTER COLUMN student_school_id SET NOT NULL",
    );
    await pool.query("ALTER TABLE students ALTER COLUMN gender SET NOT NULL");
    await pool.query("ALTER TABLE students ALTER COLUMN class_id SET NOT NULL");

    if (await columnExists("students", "grade")) {
      await pool.query("ALTER TABLE students DROP COLUMN grade CASCADE");
    }
    if (await columnExists("students", "academic_year")) {
      await pool.query(
        "ALTER TABLE students DROP COLUMN academic_year CASCADE",
      );
    }
    if (await columnExists("students", "semester")) {
      await pool.query("ALTER TABLE students DROP COLUMN semester CASCADE");
    }

    if (!(await columnExists("marks", "term_id"))) {
      await pool.query("ALTER TABLE marks ADD COLUMN term_id INTEGER");
    }

    if (
      (await columnExists("marks", "academic_year")) &&
      (await columnExists("marks", "semester"))
    ) {
      await pool.query(`
        UPDATE marks m
        SET term_id = t.term_id
        FROM terms t
        WHERE m.term_id IS NULL
          AND m.academic_year = t.academic_year
          AND m.semester = t.semester
      `);
    }

    await pool.query(`
      UPDATE marks m
      SET term_id = c.term_id
      FROM students s
      JOIN classes c ON c.class_id = s.class_id
      WHERE m.student_id = s.student_id
        AND m.term_id IS NULL
    `);

    await pool.query("UPDATE marks SET term_id = $1 WHERE term_id IS NULL", [
      defaultTermId,
    ]);

    if (!(await constraintExists("fk_marks_term"))) {
      await pool.query(`
        ALTER TABLE marks
        ADD CONSTRAINT fk_marks_term
        FOREIGN KEY (term_id) REFERENCES terms(term_id) ON DELETE RESTRICT
      `);
    }

    if (await constraintExists("unique_student_subject_semester")) {
      await pool.query(
        "ALTER TABLE marks DROP CONSTRAINT unique_student_subject_semester",
      );
    }

    if (!(await indexExists("unique_student_subject_term"))) {
      await pool.query(
        "CREATE UNIQUE INDEX unique_student_subject_term ON marks(student_id, subject_id, term_id)",
      );
    }

    if (!(await constraintExists("chk_marks_range"))) {
      await pool.query(
        "ALTER TABLE marks ADD CONSTRAINT chk_marks_range CHECK (mark_obtained >= 0 AND mark_obtained <= 100)",
      );
    }

    await pool.query("ALTER TABLE marks ALTER COLUMN term_id SET NOT NULL");

    if (await columnExists("marks", "academic_year")) {
      await pool.query("ALTER TABLE marks DROP COLUMN academic_year CASCADE");
    }
    if (await columnExists("marks", "semester")) {
      await pool.query("ALTER TABLE marks DROP COLUMN semester CASCADE");
    }

    if (!(await indexExists("idx_teacher_department"))) {
      await pool.query(
        "CREATE INDEX idx_teacher_department ON teachers(department_id)",
      );
    }
    if (!(await indexExists("idx_subject_department"))) {
      await pool.query(
        "CREATE INDEX idx_subject_department ON subjects(department_id)",
      );
    }
    if (!(await indexExists("idx_class_term"))) {
      await pool.query("CREATE INDEX idx_class_term ON classes(term_id)");
    }
    if (!(await indexExists("idx_student_class"))) {
      await pool.query("CREATE INDEX idx_student_class ON students(class_id)");
    }
    if (!(await indexExists("idx_mark_student"))) {
      await pool.query("CREATE INDEX idx_mark_student ON marks(student_id)");
    }
    if (!(await indexExists("idx_mark_subject"))) {
      await pool.query("CREATE INDEX idx_mark_subject ON marks(subject_id)");
    }
    if (!(await indexExists("idx_mark_term"))) {
      await pool.query("CREATE INDEX idx_mark_term ON marks(term_id)");
    }

    await recreateReportView();

    await pool.query("COMMIT");
    console.log("Migration completed successfully.");
  } catch (error) {
    await pool.query("ROLLBACK").catch(() => {});
    console.error("Migration failed:", error.message);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
};

runMigration();
