DROP VIEW IF EXISTS student_academic_report;
DROP VIEW IF EXISTS student_academic_report_v2;

DROP TABLE IF EXISTS marks;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS terms;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
  department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  code VARCHAR(20) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE terms (
  term_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year VARCHAR(10) NOT NULL,
  semester VARCHAR(2) NOT NULL CHECK (semester IN ('I', 'II')),
  UNIQUE (academic_year, semester)
);

CREATE TABLE teachers (
  teacher_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  department_id INTEGER NOT NULL REFERENCES departments(department_id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subjects (
  subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  department_id INTEGER NOT NULL REFERENCES departments(department_id) ON DELETE RESTRICT,
  total_mark INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE classes (
  class_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name VARCHAR(20) NOT NULL,
  grade VARCHAR(2) NOT NULL CHECK (grade IN ('9', '10', '11', '12')),
  term_id INTEGER NOT NULL REFERENCES terms(term_id) ON DELETE RESTRICT,
  homeroom_teacher_id INTEGER NOT NULL REFERENCES teachers(teacher_id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (class_name, term_id)
);

CREATE TABLE students (
  student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_school_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  gender VARCHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),
  class_id INTEGER NOT NULL REFERENCES classes(class_id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE marks (
  mark_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(student_id) ON DELETE RESTRICT,
  subject_id INTEGER NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
  term_id INTEGER NOT NULL REFERENCES terms(term_id) ON DELETE RESTRICT,
  mark_obtained INTEGER NOT NULL CHECK (mark_obtained BETWEEN 0 AND 100),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (student_id, subject_id, term_id)
);

CREATE INDEX idx_teacher_department ON teachers(department_id);
CREATE INDEX idx_subject_department ON subjects(department_id);
CREATE INDEX idx_class_term ON classes(term_id);
CREATE INDEX idx_student_class ON students(class_id);
CREATE INDEX idx_mark_student ON marks(student_id);
CREATE INDEX idx_mark_subject ON marks(subject_id);
CREATE INDEX idx_mark_term ON marks(term_id);

CREATE VIEW student_academic_report AS
SELECT
  ranked.*,
  CASE
    WHEN ranked.average_score >= 50 THEN 'PASS'
    ELSE 'FAIL'
  END AS status
FROM (
  SELECT
    s.student_id,
    s.student_school_id,
    s.name AS student_name,
    s.gender,
    c.class_name,
    c.grade,
    tm.academic_year,
    tm.semester,
    tm.maths_mark,
    tm.english_mark,
    tm.biology_mark,
    tm.chemistry_mark,
    tm.physics_mark,
    (
      COALESCE(tm.maths_mark, 0)
      + COALESCE(tm.english_mark, 0)
      + COALESCE(tm.biology_mark, 0)
      + COALESCE(tm.chemistry_mark, 0)
      + COALESCE(tm.physics_mark, 0)
    ) AS total_marks,
    ROUND((
      COALESCE(tm.maths_mark, 0)
      + COALESCE(tm.english_mark, 0)
      + COALESCE(tm.biology_mark, 0)
      + COALESCE(tm.chemistry_mark, 0)
      + COALESCE(tm.physics_mark, 0)
    )::numeric / 5, 2) AS average_score,
    RANK() OVER (
      PARTITION BY c.grade, tm.academic_year, tm.semester
      ORDER BY (
        COALESCE(tm.maths_mark, 0)
        + COALESCE(tm.english_mark, 0)
        + COALESCE(tm.biology_mark, 0)
        + COALESCE(tm.chemistry_mark, 0)
        + COALESCE(tm.physics_mark, 0)
      ) DESC
    ) AS rank
  FROM students s
  LEFT JOIN classes c ON c.class_id = s.class_id
  INNER JOIN (
    SELECT
      m.student_id,
      t.academic_year,
      t.semester,
      MAX(CASE WHEN LOWER(sub.name) = 'maths' THEN m.mark_obtained END) AS maths_mark,
      MAX(CASE WHEN LOWER(sub.name) = 'english' THEN m.mark_obtained END) AS english_mark,
      MAX(CASE WHEN LOWER(sub.name) = 'biology' THEN m.mark_obtained END) AS biology_mark,
      MAX(CASE WHEN LOWER(sub.name) = 'chemistry' THEN m.mark_obtained END) AS chemistry_mark,
      MAX(CASE WHEN LOWER(sub.name) = 'physics' THEN m.mark_obtained END) AS physics_mark
    FROM marks m
    INNER JOIN subjects sub ON sub.subject_id = m.subject_id
    INNER JOIN terms t ON t.term_id = m.term_id
    GROUP BY m.student_id, t.academic_year, t.semester
  ) tm ON tm.student_id = s.student_id
) ranked;
